# Generated by Django 2.2.13 on 2020-09-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Fish', 'Fish'), ('Beef', 'Beef'), ('White Meat', 'White Meat'), ('Sausage', 'Sausage'), ('Beverage', 'Beverage')], max_length=50, null=True),
        ),
    ]
